package logica;

public enum Categoria {

	NUMERO_NATURAL,NUMERO_REAL, CADENA_CARACTERES, IDENTIFICADOR, OPERADOR_ARITMETICO, DESCONOCIDO, OPERADOR_RELACIONAL,
	OPERADORES_LOGICOS,HEXADECIMAL,LLAVES,PARENTESIS,TERMINAL,SEPARADOR,OPERADOR_DE_INCREMENTO,OPERADORES_DE_ASIGNACION
}
