package logica;

public enum Categoria {

	NUMERO_NATURAL,NUMERO_REAL, CADENA_CARACTERES, IDENTIFICADOR, OPERADOR_ARITMETICO, DESCONOCIDO, OPERADOR_RELACIONAL,
	OPERADORES_LOGICOS,HEXADECIMAL,LLAVES_APERTURA,LLAVES_CIERRE,PARENTESIS,TERMINAL,SEPARADOR,OPERADOR_DE_INCREMENTO,OPERADOR_DECREMENTO,OPERADORES_DE_ASIGNACION,
	PALABRA_RESERVADA,COMENTARIO,PARENTESIS_APERTURA,PARENTESIS_CIERRE,CORCHETES_APERTURA,CORCHETES_CIERRE
}
