package logica;

public enum Categoria {

	ENTERO, REAL, CADENA_CARACTERES, IDENTIFICADOR, OPERADOR_ARITMETICO, DESCONOCIDO, OPERADOR_RELACIONAL,
	OPERADORES_LOGICOS,HEXADECIMAL,LLAVES,PARENTESIS,TERMINAL,SEPARADOR
}
